version: "3.8"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass
      POSTGRES_DB: proddb
    ports:
      - "5434:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

volumes:
  pgdata_prod:
